project:
  type: website
  output-dir: docs
  resources: [CNAME, images]

website:
  title: "ScienceVerse"
  site-url: https://scienceverse.github.io
  repo-url: https://github.com/scienceverse/scienceverse.github.io
  image: /images/logos/scienceverse.png
#  favicon: /images/favicon.ico
  open-graph: true
  navbar:
    logo: /images/logos/scienceverse.png
    logo-alt: "Red hexagon with SCIENCE VERSE in black art deco letters"
    right:
      - href: posts.qmd
      - text: "Talks"
        href: talks/
      - text: " "
        icon: github
        href: https://github.com/scienceverse
format:
  html:
    theme: spacelab
    primary: '#327118'
    mainfont: "Open Sans"
    monofont: "Fira Code"
    css: include/styles.scss
    fontsize: 1.1em


